#!/usr/bin/env bash

set -e

DIR="$(cd $(dirname "$0") && cd .. && pwd )"
WORKDIR=/tmp/go-workdir

function cleanup {
    rm -rf ${WORKDIR}
}

trap cleanup exit

mkdir -p ${WORKDIR}
export GOPATH=${WORKDIR}
go get github.com/cloudfoundry/hydrator/cmd/hydrate

if [ `uname` == "Linux" ]; then
  TAG="$(cat ${DIR}/config/blobs.yml | grep 'windows2019fs/windows2016fs-' |  grep -oP '\d*\.\d*\.\d*')"
else
  TAG="$(cat ${DIR}/config/blobs.yml | grep 'windows2019fs/windows2016fs-' |  grep -o '\d*\.\d*\.\d*')"
fi

${WORKDIR}/bin/hydrate \
  download \
  -image cloudfoundry/windows2016fs \
  -tag ${TAG} \
  -outputDir ${DIR}/blobs/windows2019fs

bosh create-release "${@:1}"